// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SWEN2_TourPlannerGroupProject.Data;

#nullable disable

namespace SWEN2_TourPlannerGroupProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SWEN2_TourPlannerGroupProject.Models.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Distance")
                        .HasColumnType("text");

                    b.Property<string>("EndLocation")
                        .HasColumnType("text");

                    b.Property<string>("EstimatedTime")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("RouteImagePath")
                        .HasColumnType("text");

                    b.Property<string>("RouteInformation")
                        .HasColumnType("text");

                    b.Property<string>("StartLocation")
                        .HasColumnType("text");

                    b.Property<int?>("TourId")
                        .HasColumnType("integer");

                    b.Property<string>("TransportType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("SWEN2_TourPlannerGroupProject.Models.TourLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AverageSpeed")
                        .HasColumnType("text");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<string>("Date")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Difficulty")
                        .HasColumnType("text");

                    b.Property<string>("Distance")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Rating")
                        .HasColumnType("text");

                    b.Property<string>("Report")
                        .HasColumnType("text");

                    b.Property<TimeSpan>("TimeSpan")
                        .HasColumnType("interval");

                    b.Property<double>("TotalDistance")
                        .HasColumnType("double precision");

                    b.Property<string>("TotalTime")
                        .HasColumnType("text");

                    b.Property<int?>("TourId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TourId");

                    b.ToTable("TourLogs");
                });

            modelBuilder.Entity("SWEN2_TourPlannerGroupProject.Models.TourLog", b =>
                {
                    b.HasOne("SWEN2_TourPlannerGroupProject.Models.Tour", null)
                        .WithMany("TourLogs")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SWEN2_TourPlannerGroupProject.Models.Tour", b =>
                {
                    b.Navigation("TourLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
